{
  "Header": {
    "Original": "CVE-2024-24680 [Potential denial-of-service in intcomma template filter]",
    "ID": "CVE-2024-24680",
    "Description": "[Potential denial-of-service in intcomma template filter]"
  },
  "Annotations": [
    {
      "Original": "- python-django 3:4.2.10-1",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:4.2.10-1"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2024/02/06/2",
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2024/02/06/2"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/feb/06/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9 (main)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9 (main)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc (5.0.2)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc (5.0.2)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2 (4.2.10)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2 (4.2.10)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820 (3.2.24)",
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820 (3.2.24)"
    }
  ]
}