{
  "Header": {
    "Original": "CVE-2024-3651 [potential DoS via resource consumption via specially crafted inputs to idna.encode()]",
    "ID": "CVE-2024-3651",
    "Description": "[potential DoS via resource consumption via specially crafted inputs to idna.encode()]"
  },
  "Annotations": [
    {
      "Original": "- python-idna \u003cunfixed\u003e",
      "Type": "package",
      "Package": "python-idna",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2274779",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2274779"
    }
  ]
}