{
  "Header": {
    "Original": "CVE-2022-48566 (An issue was discovered in compare_digest in Lib/hmac.py in Python thr ...)",
    "ID": "CVE-2022-48566",
    "Description": "(An issue was discovered in compare_digest in Lib/hmac.py in Python thr ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.9 3.9.0~b4-1",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "fixed",
      "Version": "3.9.0~b4-1"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python2.7 \u003cignored\u003e (Unsupported in Bullseye, only included to build a few applications)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python2.7",
      "Kind": "ignored",
      "Description": "Unsupported in Bullseye, only included to build a few applications"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/8183e11d87388e4e44e3242c42085b87a878f781",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/8183e11d87388e4e44e3242c42085b87a878f781"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/84968",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/84968"
    }
  ]
}