{
  "Header": {
    "Original": "CVE-2025-3136 (A vulnerability, which was classified as problematic, has been found i ...)",
    "ID": "CVE-2025-3136",
    "Description": "(A vulnerability, which was classified as problematic, has been found i ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/149821",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/149821"
    }
  ]
}